name: Ejecución Diaria de Pruebas de API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. Checkout del código fuente
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Setup Java JDK
      - name: Configurar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Dar permisos al gradlew
      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      # 4. Ejecutar los tests (genera build/allure-results)
      - name: Ejecutar tests de API
        run: ./gradlew test

      # 5. Descargar historial anterior de reportes (de gh-pages)
      - name: Descargar historial de reportes
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      # 6. Generar el Allure report con historial
      - name: Generar Allure Report con historial
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_history: allure-history

      # 7. Publicar Allure report en gh-pages (GitHub Pages)
      - name: Publicar reporte en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
